# Generated by Django 4.0.4 on 2022-07-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_section2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section2',
            new_name='Section',
        ),
    ]
